#!/bin/bash

set -euo pipefail

>&2 echo "::group::Get changelog comment"
trap ">&2 echo '::endgroup::'" EXIT # bash equivalent of defer func()

# Get the changelog as it would rendered on a pull request comment.

PREVIOUS_VERSION="$1"
CHANGELOG_REQUIRED="${2:-"true"}"
ADDITIONAL_COMMENT="${3:-""}"

CHANGELOG=$(./.github/scripts/get-changelog "${PREVIOUS_VERSION}" --with-commit="${ADDITIONAL_COMMENT}" --unreleased --strip=all)
if [ -n "${CHANGELOG}" ]; then
  echo -n "${CHANGELOG}"
else
  echo -n "n/a"
  if [ "$CHANGELOG_REQUIRED" != "false" ]; then
    >&2 echo "::error::Changelog not present"
    exit 1
  fi
fi
