permissions: write-all # Equivalent to default permissions plus id-token: write
env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: false
name: Publish Crates

on:
  workflow_call:
    inputs:
      version:
        required: true
        description: "Version to produce"
        type: string

jobs:
  cargo-publish:
    name: Cargo Publish
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - uses: actions/checkout@v3
      - run: git fetch --tags && git checkout tags/v${{ inputs.version }}
      - uses: Swatinem/rust-cache@6720f05bc48b77f96918929a9019fb2203ff71f8 # v2.0.0
      - uses: dtolnay/rust-toolchain@415f4eec04da36a50da617131b6bd78f0282958b # v1.70.0
        with:
          toolchain: stable
      - env:
          CARGO_REGISTRY_TOKEN: ${{ steps.esc-secrets.outputs.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p pulumi-watch
